### ISSUE TITLE
search is changing soon

### ISSUE THREAD

**Issue by alandownie** [SweetHawk/rightgif#1]
- [x] /search will become /search/web for websites
- [x] search will return a json object with just the url
- [ ] we will soon be adding CSRF checks, so we'll need to discuss how to progress beyond that...

**Comment by vbrendel** [comment]
How about you give me an app key and I pass the requests server side?

**Comment by alandownie** [comment]
yeah I'm in the midst of abstracting the search API, so once that is done I'll be able to hack in a key check

**Comment by alandownie** [comment]
we changed this, but then changed it back... so it's just /search still

**Comment by vbrendel** [comment]
Adapted new version to search's new json result.

Could you pls maintain current API without checking CSRF for a little while even after introducing new API? Zendesk app updates can take a few weeks.
