### ISSUE TITLE
Getting 500 errors

### ISSUE THREAD

**Issue by justin-robinson** [SweetHawk/rightgif#2]
The url used to get gifs is returning 500 errors
![image](https://cloud.githubusercontent.com/assets/3090489/20843364/ed517392-b86f-11e6-87f6-df674287a674.png)

https://zendesk.sweethawk.co/rightgif

**Comment by vbrendel** [comment]
Hi @justin-robinson thanks for reporting and for using the RIghtGIF app. The issue was that some information needed wasn't sent by the Zendesk app, this was intermittent and appeared to have been resolved by Zendesk since. Please let us know if any issues persist.

**Comment by justin-robinson** [comment]
Thanks for the quick fix!

**Comment by vbrendel** [comment]
Just a quick note this API is only designed for use by the free RightGIF app for Zendesk.

For API access to RightGIF, contact:
https://rightgif.com
